### PR TITLE
setup.py and change regarding PYTHONPATH

### PR DESCRIPTION
**Pull request by mbrock**
This branch works with my Nix packaging that will be uploaded to the Dapphub channel soon.

### CODE REVIEW

**Comment by reverendus** [comment]
All fine, thanks for the nix package! Just one question: what's the reason behind removing explicit setting of `PYTHONPATH` from the scripts in `bin`? Does it clash with nix packaging somehow...?
 Without that, I cannot go into `bin` and execute any of these scripts. It will only work if the current working directory is the parent one...

**Comment by mbrock** [comment]
It kind of clashes with Nix because it wants to set its own `PYTHONPATH` to a path that includes where it has installed the Keeper package and some other system paths I guess.

Maybe the `bin` scripts could append to the `NIXPATH` instead of overriding, that seems like it would work for both situations... I'll try that.

**Comment by reverendus** [comment]
Thanks!

**Comment by reverendus** [comment]
Any news on this @mbrock ?

**Comment by mbrock** [comment]
I added a commit that makes it append to PYTHONPATH.

**Comment by reverendus** [comment]
Thanks!

**Pull request merged**
